import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Navbar";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import Footer from "./footer";
import ContactCard from "../../components/ui/quickcontacts";
import { TabProvider } from "../../context/TabContext";
import QuickContact from "./quickContact";
import GoldHelpDialogWrapper from "./gold-contact-wrapper"; // ✅ Import here
import React from "react";
import { DialogProvider } from "../../context/handleDialog";

// Fonts
const poppins = localFont({
  src: [
    {
      path: "../../public/fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-inter",
  display: "swap",
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} antialiased`}>
        <DialogProvider>
        <TabProvider>
          <div className=" sm-hidden mg-fixed lg-fixed  top-0 left-0 w-full z-50">
            <Navbar />
          </div>
          {children}
          <QuickContact />
          <GoldHelpDialogWrapper /> {/* ✅ This is client now */}
          <Footer />
          <div className="fixed bottom-4 right-4 z-50">
            <ContactCard />
          </div>
        </TabProvider>
        </DialogProvider>
      </body>
    </html>
  );
}
